Improved design of Cards and minor improvements
curiomind-e-learning/curiomind pull request #16
Opened 2022-03-01 14:24 UTC by VishwaGauravIn

Previews:
![image](https://user-images.githubusercontent.com/81325730/156186520-cfce758e-d1f1-465e-818c-ed4fd766c085.png)
![image](https://user-images.githubusercontent.com/81325730/156186650-049a327f-87b4-4b04-8dee-9238ca948334.png)

2022-03-02 15:24 UTC, geekymeeky requested changes
Good work @VishwaGauravIn  

PS: Start working on the issue only after it has been assigned to you and each PR must be associated with an issue. Please see the contribution guidelines for further information.

Create a new issue for it, and this PR is ready to be merged.

2022-03-10 13:44 UTC, VishwaGauravIn commented
> Good work @VishwaGauravIn
> 
> PS: Start working on the issue only after it has been assigned to you and each PR must be associated with an issue. Please see the contribution guidelines for further information.
> 
> Create a new issue for it, and this PR is ready to be merged.

Thanks Srijan , Sorry for late reply. I was busy in shifting. I will create the Issue and attach it.

2022-03-11 10:17 UTC, VishwaGauravIn commented
Fixed issue #38

2022-03-17 10:51 UTC, geekymeeky approved these changes

2022-03-17 10:51 UTC, merged